-- Insert demo emails for the demo account
INSERT INTO emails (
  id,
  user_id,
  message_id,
  thread_id,
  subject,
  sender_name,
  sender_email,
  recipient_emails,
  body_text,
  body_html,
  received_at,
  is_read,
  is_starred,
  is_important,
  labels,
  has_attachments,
  created_at,
  updated_at
) VALUES 
-- Welcome email
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'welcome-001',
  'thread-welcome-001',
  'Welcome to HiSpeed Mail! 🚀',
  'HiSpeed Team',
  'team@hispeedmail.com',
  ARRAY['demo@hispeedmail.com'],
  'Welcome to HiSpeed Mail! We''re excited to have you on board. Get ready for lightning-fast email management.',
  '<div><h2>Welcome to HiSpeed Mail! 🚀</h2><p>We''re excited to have you on board. Get ready for lightning-fast email management with features like:</p><ul><li>⚡ Instant search</li><li>🎯 Smart filtering</li><li>📱 Mobile-first design</li><li>🔒 Secure encryption</li></ul><p>Happy emailing!</p><p>The HiSpeed Team</p></div>',
  now() - interval '1 hour',
  false,
  true,
  true,
  ARRAY['inbox', 'important'],
  false,
  now(),
  now()
),
-- Project update
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'project-update-001',
  'thread-project-001',
  'Q4 Project Updates - Action Required',
  'Sarah Johnson',
  'sarah.johnson@company.com',
  ARRAY['demo@hispeedmail.com', 'team@company.com'],
  'Hi team, Here are the Q4 project updates. Please review the attached documents and provide feedback by Friday.',
  '<div><p>Hi team,</p><p>Here are the Q4 project updates:</p><ul><li>✅ Phase 1 completed ahead of schedule</li><li>🔄 Phase 2 in progress (85% complete)</li><li>📅 Phase 3 starting next week</li></ul><p><strong>Action Required:</strong> Please review the attached documents and provide feedback by Friday.</p><p>Best regards,<br>Sarah</p></div>',
  now() - interval '2 hours',
  false,
  false,
  true,
  ARRAY['inbox', 'work'],
  true,
  now(),
  now()
),
-- Newsletter
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'newsletter-001',
  'thread-newsletter-001',
  'Weekly Tech Digest - AI Breakthroughs & More',
  'Tech Weekly',
  'newsletter@techweekly.com',
  ARRAY['demo@hispeedmail.com'],
  'This week in tech: Major AI breakthroughs, new framework releases, and industry insights you can''t miss.',
  '<div><h2>Weekly Tech Digest</h2><p>This week in tech:</p><ul><li>🤖 Major AI breakthroughs in language models</li><li>⚛️ React 19 beta released</li><li>🚀 New deployment tools launched</li><li>💡 Industry insights from top leaders</li></ul><p><a href="#" style="color: #3b82f6;">Read full newsletter →</a></p></div>',
  now() - interval '3 hours',
  true,
  false,
  false,
  ARRAY['inbox', 'newsletters'],
  false,
  now(),
  now()
),
-- Meeting invite
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'meeting-001',
  'thread-meeting-001',
  'Team Standup - Tomorrow 10 AM',
  'Alex Chen',
  'alex.chen@company.com',
  ARRAY['demo@hispeedmail.com', 'team@company.com'],
  'Quick reminder about our team standup tomorrow at 10 AM. We''ll be discussing sprint progress and blockers.',
  '<div><p>Hi everyone,</p><p>Quick reminder about our team standup tomorrow at 10 AM.</p><p><strong>Agenda:</strong></p><ul><li>Sprint progress review</li><li>Current blockers discussion</li><li>Next week planning</li></ul><p>Meeting link: <a href="#" style="color: #3b82f6;">Join Zoom Meeting</a></p><p>See you there!<br>Alex</p></div>',
  now() - interval '4 hours',
  false,
  false,
  false,
  ARRAY['inbox', 'meetings'],
  false,
  now(),
  now()
),
-- Security alert
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'security-001',
  'thread-security-001',
  'Security Alert: New Login Detected',
  'Security Team',
  'security@hispeedmail.com',
  ARRAY['demo@hispeedmail.com'],
  'We detected a new login to your account from a new device. If this was you, no action needed.',
  '<div><h3>🔒 Security Alert</h3><p>We detected a new login to your account:</p><ul><li><strong>Device:</strong> Chrome on macOS</li><li><strong>Location:</strong> San Francisco, CA</li><li><strong>Time:</strong> Today at 2:30 PM</li></ul><p>If this was you, no action is needed. If not, please <a href="#" style="color: #ef4444;">secure your account immediately</a>.</p></div>',
  now() - interval '5 hours',
  true,
  false,
  true,
  ARRAY['inbox', 'security'],
  false,
  now(),
  now()
),
-- Social notification
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'social-001',
  'thread-social-001',
  'You have 3 new connections on LinkedIn',
  'LinkedIn',
  'notifications@linkedin.com',
  ARRAY['demo@hispeedmail.com'],
  'Great news! You have 3 new connection requests waiting for your response.',
  '<div><h3>New Connections Waiting</h3><p>You have <strong>3 new connection requests</strong> from:</p><ul><li>👤 Maria Rodriguez - Product Manager at TechCorp</li><li>👤 David Kim - Senior Developer at StartupXYZ</li><li>👤 Jennifer Liu - UX Designer at DesignStudio</li></ul><p><a href="#" style="background: #0077b5; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px;">View Requests</a></p></div>',
  now() - interval '6 hours',
  true,
  false,
  false,
  ARRAY['inbox', 'social'],
  false,
  now(),
  now()
),
-- Invoice
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'invoice-001',
  'thread-invoice-001',
  'Invoice #INV-2024-001 - Payment Due',
  'Billing Department',
  'billing@webservices.com',
  ARRAY['demo@hispeedmail.com'],
  'Your invoice for web hosting services is now due. Please process payment by the due date to avoid service interruption.',
  '<div><h3>Invoice Due</h3><p><strong>Invoice #:</strong> INV-2024-001<br><strong>Amount:</strong> $99.00<br><strong>Due Date:</strong> December 15, 2024</p><p><strong>Services:</strong></p><ul><li>Web Hosting - Premium Plan</li><li>SSL Certificate</li><li>Daily Backups</li></ul><p><a href="#" style="background: #16a34a; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px;">Pay Now</a></p></div>',
  now() - interval '1 day',
  false,
  true,
  true,
  ARRAY['inbox', 'billing'],
  true,
  now(),
  now()
),
-- Promotional
(
  gen_random_uuid(),
  '550e8400-e29b-41d4-a716-446655440000',
  'promo-001',
  'thread-promo-001',
  '🎉 Black Friday Sale - 50% Off Everything!',
  'TechStore',
  'deals@techstore.com',
  ARRAY['demo@hispeedmail.com'],
  'Don''t miss our biggest sale of the year! 50% off all tech products for a limited time.',
  '<div style="text-align: center;"><h2>🎉 BLACK FRIDAY MEGA SALE</h2><h3 style="color: #ef4444;">50% OFF EVERYTHING!</h3><p>Limited time offer on all tech products:</p><ul style="text-align: left;"><li>💻 Laptops & Computers</li><li>📱 Smartphones & Tablets</li><li>🎧 Audio & Accessories</li><li>⌚ Smart Watches</li></ul><p><a href="#" style="background: #ef4444; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">SHOP NOW</a></p><p style="font-size: 12px; color: #666;">Sale ends December 1st. Terms apply.</p></div>',
  now() - interval '1 day',
  true,
  false,
  false,
  ARRAY['inbox', 'promotions'],
  false,
  now(),
  now()
);
